# Generated by Django 5.2 on 2025-06-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grandywoods_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="guests/")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
